class_name SquirrelAwaySubtilesManifest
extends SubtileCorner


# NOTE:
# -   This must to be kept in-sync with the corresponding tile-set image.
# -   Autotile bitmasks must also be defined using the normal Godot TileSet
#     editor.
const SUBTILES := {
    error_indicator_subtile_position = Vector2(10,1),
    # FIXME: LEFT OFF HERE: ----------------------------------------------
    # - Update this with the current subtiles.
    
    # FIXME: LEFT OFF HERE: ------------ Add inbound properties.
#     inbound_t_bl?: SubtileCorner,
#     inbound_t_br?: SubtileCorner,
#     inbound_b_tl?: SubtileCorner,
#     inbound_b_tr?: SubtileCorner,
#     inbound_l_tr?: SubtileCorner,
#     inbound_l_br?: SubtileCorner,
#     inbound_r_tl?: SubtileCorner,
#     inbound_r_bl?: SubtileCorner,
    subtiles = [
        {
            p = Vector2(0,0),
            a = [90],
            tl = EXT_90_90_CONVEX,
            tr = EXT_90_90_CONVEX,
            bl = EXT_90V,
            br = EXT_90V,
        },
        {
            p = Vector2(1,0),
            a = [90],
            tl = EXT_90_90_CONVEX,
            tr = EXT_90H,
            bl = EXT_90V,
            br = EXT_90_90_CONCAVE,
        },
        {
            p = Vector2(2,0),
            a = [90],
            tl = EXT_90H,
            tr = EXT_90H,
            bl = EXT_90_90_CONCAVE,
            br = EXT_90_90_CONCAVE,
        },
        {
            p = Vector2(3,0),
            a = [90],
            tl = EXT_90H,
            tr = EXT_90_90_CONVEX,
            bl = EXT_90_90_CONCAVE,
            br = EXT_90V,
        },
        {
            p = Vector2(4,0),
            a = [90],
            tl = EXT_INT_90_90_CONVEX,
            tr = EXT_90_90_CONCAVE,
            bl = EXT_90_90_CONCAVE,
            br = EXT_90_90_CONCAVE,
        },
        {
            p = Vector2(5,0),
            a = [90],
            tl = EXT_90H,
            tr = EXT_90H,
            bl = EXT_90_90_CONCAVE,
            br = EXT_INT_90_90_CONVEX,
        },
        {
            p = Vector2(6,0),
            a = [90],
            tl = EXT_90H,
            tr = EXT_90H,
            bl = EXT_INT_90_90_CONVEX,
            br = EXT_90_90_CONCAVE,
        },
        {
            p = Vector2(7,0),
            a = [90],
            tl = EXT_90_90_CONCAVE,
            tr = EXT_INT_90_90_CONVEX,
            bl = EXT_90_90_CONCAVE,
            br = EXT_90_90_CONCAVE,
        },
        {
            p = Vector2(8,0),
            a = [90],
            tl = EXT_90_90_CONVEX,
            tr = EXT_90H,
            bl = EXT_90V,
            br = EXT_INT_90_90_CONVEX,
        },
        {
            p = Vector2(9,0),
            a = [90],
            tl = EXT_90_90_CONCAVE,
            tr = EXT_90_90_CONCAVE,
            bl = EXT_INT_90H,
            br = EXT_INT_90H,
        },
        {
            p = Vector2(10,0),
            a = [90],
            tl = EXT_90H,
            tr = EXT_90H,
            bl = EXT_INT_90H,
            br = EXT_INT_90H,
        },
        {
            p = Vector2(11,0),
            a = [90],
            tl = EXT_90H,
            tr = EXT_90_90_CONVEX,
            bl = EXT_INT_90_90_CONVEX,
            br = EXT_90V,
        },
        {
            p = Vector2(0,1),
            a = [90,45,27],
            tl = EXT_90V,
            tr = EXT_90V,
            bl = EXT_90V,
            br = EXT_90V,
        },
        {
            p = Vector2(1,1),
            a = [90],
            tl = EXT_90V,
            tr = EXT_90_90_CONCAVE,
            bl = EXT_90V,
            br = EXT_90_90_CONCAVE,
        },
        {
            p = Vector2(2,1),
            a = [90],
            tl = EXT_90_90_CONCAVE,
            tr = EXT_90_90_CONCAVE,
            bl = EXT_90_90_CONCAVE,
            br = EXT_90_90_CONCAVE,
        },
        {
            p = Vector2(3,1),
            a = [90],
            tl = EXT_90_90_CONCAVE,
            tr = EXT_90V,
            bl = EXT_90_90_CONCAVE,
            br = EXT_90V,
        },
        {
            p = Vector2(4,1),
            a = [90],
            tl = EXT_90V,
            tr = EXT_90_90_CONCAVE,
            bl = EXT_90V,
            br = EXT_INT_90_90_CONVEX,
        },
        {
            p = Vector2(5,1),
            a = [90],
            tl = EXT_90_90_CONCAVE,
            tr = EXT_INT_90V,
            bl = EXT_INT_90H,
            br = EXT_INT_90_90_CONCAVE,
        },
        {
            p = Vector2(6,1),
            a = [90],
            tl = EXT_INT_90V,
            tr = EXT_90_90_CONCAVE,
            bl = EXT_INT_90_90_CONCAVE,
            br = EXT_INT_90H,
        },
        {
            p = Vector2(7,1),
            a = [90],
            tl = EXT_90_90_CONCAVE,
            tr = EXT_90V,
            bl = EXT_INT_90_90_CONVEX,
            br = EXT_90V,
        },
        {
            p = Vector2(8,1),
            a = [90],
            tl = EXT_90V,
            tr = EXT_INT_90V,
            bl = EXT_90V,
            br = EXT_INT_90V,
        },
        {
            p = Vector2(9,1),
            a = [90],
            tl = EXT_90_90_CONCAVE,
            tr = EXT_INT_90_90_CONVEX,
            bl = EXT_INT_90_90_CONVEX,
            br = EXT_90_90_CONCAVE,
        },
#        {
#            p = Vector2(10,1),
#            a = [90],
#            tl = ERROR,
#            tr = ERROR,
#            bl = ERROR,
#            br = ERROR,
#        },
        {
            p = Vector2(11,1),
            a = [90],
            tl = EXT_INT_90V,
            tr = EXT_90_90_CONCAVE,
            bl = EXT_INT_90V,
            br = EXT_90_90_CONCAVE,
        },
        {
            p = Vector2(0,2),
            a = [90],
            tl = EXT_90V,
            tr = EXT_90V,
            bl = EXT_90_90_CONVEX,
            br = EXT_90_90_CONVEX,
        },
        {
            p = Vector2(1,2),
            a = [90],
            tl = EXT_90V,
            tr = EXT_90_90_CONCAVE,
            bl = EXT_90_90_CONVEX,
            br = EXT_90H,
        },
        {
            p = Vector2(2,2),
            a = [90],
            tl = EXT_90_90_CONCAVE,
            tr = EXT_90_90_CONCAVE,
            bl = EXT_90H,
            br = EXT_90H,
        },
        {
            p = Vector2(3,2),
            a = [90],
            tl = EXT_90_90_CONCAVE,
            tr = EXT_90V,
            bl = EXT_90H,
            br = EXT_90_90_CONVEX,
        },
        {
            p = Vector2(4,2),
            a = [90],
            tl = EXT_90V,
            tr = EXT_INT_90_90_CONVEX,
            bl = EXT_90V,
            br = EXT_90_90_CONCAVE,
        },
        {
            p = Vector2(5,2),
            a = [90],
            tl = EXT_INT_90H,
            tr = EXT_INT_90_90_CONCAVE,
            bl = EXT_90_90_CONCAVE,
            br = EXT_INT_90V,
        },
        {
            p = Vector2(6,2),
            a = [90],
            tl = EXT_INT_90_90_CONCAVE,
            tr = EXT_INT_90H,
            bl = EXT_INT_90V,
            br = EXT_90_90_CONCAVE,
        },
        {
            p = Vector2(7,2),
            a = [90],
            tl = EXT_INT_90_90_CONVEX,
            tr = EXT_90V,
            bl = EXT_90_90_CONCAVE,
            br = EXT_90V,
        },
        {
            p = Vector2(8,2),
            a = [90],
            tl = EXT_90_90_CONCAVE,
            tr = EXT_INT_90V,
            bl = EXT_90_90_CONCAVE,
            br = EXT_INT_90V,
        },
#        {
#            p = Vector2(9,2),
#            a = [90],
#            tl = FULLY_INTERIOR,
#            tr = FULLY_INTERIOR,
#            bl = FULLY_INTERIOR,
#            br = FULLY_INTERIOR,
#        },
        {
            p = Vector2(10,2),
            a = [90],
            tl = EXT_INT_90_90_CONVEX,
            tr = EXT_90_90_CONCAVE,
            bl = EXT_90_90_CONCAVE,
            br = EXT_INT_90_90_CONVEX,
        },
        {
            p = Vector2(11,2),
            a = [90],
            tl = EXT_INT_90V,
            tr = EXT_90V,
            bl = EXT_INT_90V,
            br = EXT_90V,
        },
        {
            p = Vector2(0,3),
            a = [90],
            tl = EXT_90_90_CONVEX,
            tr = EXT_90_90_CONVEX,
            bl = EXT_90_90_CONVEX,
            br = EXT_90_90_CONVEX,
        },
        {
            p = Vector2(1,3),
            a = [90],
            tl = EXT_90_90_CONVEX,
            tr = EXT_90H,
            bl = EXT_90_90_CONVEX,
            br = EXT_90H,
        },
        {
            p = Vector2(2,3),
            a = [90,45,27],
            tl = EXT_90H,
            tr = EXT_90H,
            bl = EXT_90H,
            br = EXT_90H,
        },
        {
            p = Vector2(3,3),
            a = [90],
            tl = EXT_90H,
            tr = EXT_90_90_CONVEX,
            bl = EXT_90H,
            br = EXT_90_90_CONVEX,
        },
        {
            p = Vector2(4,3),
            a = [90],
            tl = EXT_90_90_CONCAVE,
            tr = EXT_90_90_CONCAVE,
            bl = EXT_INT_90_90_CONVEX,
            br = EXT_90_90_CONCAVE,
        },
        {
            p = Vector2(5,3),
            a = [90],
            tl = EXT_90_90_CONCAVE,
            tr = EXT_INT_90_90_CONVEX,
            bl = EXT_90H,
            br = EXT_90H,
        },
        {
            p = Vector2(6,3),
            a = [90],
            tl = EXT_INT_90_90_CONVEX,
            tr = EXT_90_90_CONCAVE,
            bl = EXT_90H,
            br = EXT_90H,
        },
        {
            p = Vector2(7,3),
            a = [90],
            tl = EXT_90_90_CONCAVE,
            tr = EXT_90_90_CONCAVE,
            bl = EXT_90_90_CONCAVE,
            br = EXT_INT_90_90_CONVEX,
        },
        {
            p = Vector2(8,3),
            a = [90],
            tl = EXT_90V,
            tr = EXT_INT_90_90_CONVEX,
            bl = EXT_90_90_CONVEX,
            br = EXT_90H,
        },
        {
            p = Vector2(9,3),
            a = [90],
            tl = EXT_INT_90H,
            tr = EXT_INT_90H,
            bl = EXT_90H,
            br = EXT_90H,
        },
        {
            p = Vector2(10,3),
            a = [90],
            tl = EXT_INT_90H,
            tr = EXT_INT_90H,
            bl = EXT_90_90_CONCAVE,
            br = EXT_90_90_CONCAVE,
        },
        {
            p = Vector2(11,3),
            a = [90],
            tl = EXT_INT_90_90_CONVEX,
            tr = EXT_90V,
            bl = EXT_90H,
            br = EXT_90_90_CONVEX,
        },
    ],
}
