class_name SquirrelAwaySubtileQuadrantsManifest
extends SubtileCorner


# NOTE: This must be kept in-sync with the corresponding tile-set image.
const MANIFEST := [
    # FIXME: LEFT OFF HERE: ----------------------------------------------
    # - Update this with the current subtiles.
    
    {
        p = Vector2(0,0),
        a = 90,
        tl = EXT_90_90_CONVEX,
        tr = EXT_90_90_CONVEX,
        bl = EXT_90V,
        br = EXT_90V,
    },
    {
        p = Vector2(1,0),
        a = 90,
        tl = EXT_90_90_CONVEX,
        tr = EXT_90H,
        bl = EXT_90V,
        br = EXT_CLIPPED_90_90,
    },
    {
        p = Vector2(2,0),
        a = 90,
        tl = EXT_90H,
        tr = EXT_90H,
        bl = EXT_CLIPPED_90_90,
        br = EXT_CLIPPED_90_90,
    },
    {
        p = Vector2(3,0),
        a = 90,
        tl = EXT_90H,
        tr = EXT_90_90_CONVEX,
        bl = EXT_CLIPPED_90_90,
        br = EXT_90V,
    },
    {
        p = Vector2(4,0),
        a = 90,
        tl = EXTERIOR,
        tr = EXT_CLIPPED_90_90,
        bl = EXT_CLIPPED_90_90,
        br = EXT_CLIPPED_90_90,
    },
    {
        p = Vector2(5,0),
        a = 90,
        tl = EXT_90H,
        tr = EXT_90H,
        bl = EXT_CLIPPED_90_90,
        br = EXTERIOR,
    },
    {
        p = Vector2(6,0),
        a = 90,
        tl = EXT_90H,
        tr = EXT_90H,
        bl = EXTERIOR,
        br = EXT_CLIPPED_90_90,
    },
    {
        p = Vector2(7,0),
        a = 90,
        tl = EXT_CLIPPED_90_90,
        tr = EXTERIOR,
        bl = EXT_CLIPPED_90_90,
        br = EXT_CLIPPED_90_90,
    },
    {
        p = Vector2(8,0),
        a = 90,
        tl = EXT_90_90_CONVEX,
        tr = EXT_90H,
        bl = EXT_90V,
        br = EXTERIOR,
    },
    {
        p = Vector2(9,0),
        a = 90,
        tl = EXT_CLIPPED_90_90,
        tr = EXT_CLIPPED_90_90,
        bl = EXTERIOR,
        br = EXTERIOR,
    },
    {
        p = Vector2(10,0),
        a = 90,
        tl = EXT_90H,
        tr = EXT_90H,
        bl = EXTERIOR,
        br = EXTERIOR,
    },
    {
        p = Vector2(11,0),
        a = 90,
        tl = EXT_90H,
        tr = EXT_90_90_CONVEX,
        bl = EXTERIOR,
        br = EXT_90V,
    },
    {
        p = Vector2(0,1),
        a = [90,45,27],
        tl = EXT_90V,
        tr = EXT_90V,
        bl = EXT_90V,
        br = EXT_90V,
    },
    {
        p = Vector2(1,1),
        a = 90,
        tl = EXT_90V,
        tr = EXT_CLIPPED_90_90,
        bl = EXT_90V,
        br = EXT_CLIPPED_90_90,
    },
    {
        p = Vector2(2,1),
        a = 90,
        tl = EXT_CLIPPED_90_90,
        tr = EXT_CLIPPED_90_90,
        bl = EXT_CLIPPED_90_90,
        br = EXT_CLIPPED_90_90,
    },
    {
        p = Vector2(3,1),
        a = 90,
        tl = EXT_CLIPPED_90_90,
        tr = EXT_90V,
        bl = EXT_CLIPPED_90_90,
        br = EXT_90V,
    },
    {
        p = Vector2(4,1),
        a = 90,
        tl = EXT_90V,
        tr = EXT_CLIPPED_90_90,
        bl = EXT_90V,
        br = EXTERIOR,
    },
    {
        p = Vector2(5,1),
        a = 90,
        tl = EXT_CLIPPED_90_90,
        tr = EXTERIOR,
        bl = EXTERIOR,
        br = EXTERIOR,
    },
    {
        p = Vector2(6,1),
        a = 90,
        tl = EXTERIOR,
        tr = EXT_CLIPPED_90_90,
        bl = EXTERIOR,
        br = EXTERIOR,
    },
    {
        p = Vector2(7,1),
        a = 90,
        tl = EXT_CLIPPED_90_90,
        tr = EXT_90V,
        bl = EXTERIOR,
        br = EXT_90V,
    },
    {
        p = Vector2(8,1),
        a = 90,
        tl = EXT_90V,
        tr = EXTERIOR,
        bl = EXT_90V,
        br = EXTERIOR,
    },
    {
        p = Vector2(9,1),
        a = 90,
        tl = EXT_CLIPPED_90_90,
        tr = EXTERIOR,
        bl = EXTERIOR,
        br = EXT_CLIPPED_90_90,
    },
#        {
#            p = Vector2(10,1),
#            a = 90,
#            tl = UNKNOWN,
#            tr = UNKNOWN,
#            bl = UNKNOWN,
#            br = UNKNOWN,
#        },
    {
        p = Vector2(11,1),
        a = 90,
        tl = EXTERIOR,
        tr = EXT_CLIPPED_90_90,
        bl = EXTERIOR,
        br = EXT_CLIPPED_90_90,
    },
    {
        p = Vector2(0,2),
        a = 90,
        tl = EXT_90V,
        tr = EXT_90V,
        bl = EXT_90_90_CONVEX,
        br = EXT_90_90_CONVEX,
    },
    {
        p = Vector2(1,2),
        a = 90,
        tl = EXT_90V,
        tr = EXT_CLIPPED_90_90,
        bl = EXT_90_90_CONVEX,
        br = EXT_90H,
    },
    {
        p = Vector2(2,2),
        a = 90,
        tl = EXT_CLIPPED_90_90,
        tr = EXT_CLIPPED_90_90,
        bl = EXT_90H,
        br = EXT_90H,
    },
    {
        p = Vector2(3,2),
        a = 90,
        tl = EXT_CLIPPED_90_90,
        tr = EXT_90V,
        bl = EXT_90H,
        br = EXT_90_90_CONVEX,
    },
    {
        p = Vector2(4,2),
        a = 90,
        tl = EXT_90V,
        tr = EXTERIOR,
        bl = EXT_90V,
        br = EXT_CLIPPED_90_90,
    },
    {
        p = Vector2(5,2),
        a = 90,
        tl = EXTERIOR,
        tr = EXTERIOR,
        bl = EXT_CLIPPED_90_90,
        br = EXTERIOR,
    },
    {
        p = Vector2(6,2),
        a = 90,
        tl = EXTERIOR,
        tr = EXTERIOR,
        bl = EXTERIOR,
        br = EXT_CLIPPED_90_90,
    },
    {
        p = Vector2(7,2),
        a = 90,
        tl = EXTERIOR,
        tr = EXT_90V,
        bl = EXT_CLIPPED_90_90,
        br = EXT_90V,
    },
    {
        p = Vector2(8,2),
        a = 90,
        tl = EXT_CLIPPED_90_90,
        tr = EXTERIOR,
        bl = EXT_CLIPPED_90_90,
        br = EXTERIOR,
    },
#        {
#            p = Vector2(9,2),
#            a = 90,
#            tl = EXTERIOR,
#            tr = EXTERIOR,
#            bl = EXTERIOR,
#            br = EXTERIOR,
#        },
    {
        p = Vector2(10,2),
        a = 90,
        tl = EXTERIOR,
        tr = EXT_CLIPPED_90_90,
        bl = EXT_CLIPPED_90_90,
        br = EXTERIOR,
    },
    {
        p = Vector2(11,2),
        a = 90,
        tl = EXTERIOR,
        tr = EXT_90V,
        bl = EXTERIOR,
        br = EXT_90V,
    },
    {
        p = Vector2(0,3),
        a = 90,
        tl = EXT_90_90_CONVEX,
        tr = EXT_90_90_CONVEX,
        bl = EXT_90_90_CONVEX,
        br = EXT_90_90_CONVEX,
    },
    {
        p = Vector2(1,3),
        a = 90,
        tl = EXT_90_90_CONVEX,
        tr = EXT_90H,
        bl = EXT_90_90_CONVEX,
        br = EXT_90H,
    },
    {
        p = Vector2(2,3),
        a = [90,45,27],
        tl = EXT_90H,
        tr = EXT_90H,
        bl = EXT_90H,
        br = EXT_90H,
    },
    {
        p = Vector2(3,3),
        a = 90,
        tl = EXT_90H,
        tr = EXT_90_90_CONVEX,
        bl = EXT_90H,
        br = EXT_90_90_CONVEX,
    },
    {
        p = Vector2(4,3),
        a = 90,
        tl = EXT_CLIPPED_90_90,
        tr = EXT_CLIPPED_90_90,
        bl = EXTERIOR,
        br = EXT_CLIPPED_90_90,
    },
    {
        p = Vector2(5,3),
        a = 90,
        tl = EXT_CLIPPED_90_90,
        tr = EXTERIOR,
        bl = EXT_90H,
        br = EXT_90H,
    },
    {
        p = Vector2(6,3),
        a = 90,
        tl = EXTERIOR,
        tr = EXT_CLIPPED_90_90,
        bl = EXT_90H,
        br = EXT_90H,
    },
    {
        p = Vector2(7,3),
        a = 90,
        tl = EXT_CLIPPED_90_90,
        tr = EXT_CLIPPED_90_90,
        bl = EXT_CLIPPED_90_90,
        br = EXTERIOR,
    },
    {
        p = Vector2(8,3),
        a = 90,
        tl = EXT_90V,
        tr = EXTERIOR,
        bl = EXT_90_90_CONVEX,
        br = EXT_90H,
    },
    {
        p = Vector2(9,3),
        a = 90,
        tl = EXTERIOR,
        tr = EXTERIOR,
        bl = EXT_90H,
        br = EXT_90H,
    },
    {
        p = Vector2(10,3),
        a = 90,
        tl = EXTERIOR,
        tr = EXTERIOR,
        bl = EXT_CLIPPED_90_90,
        br = EXT_CLIPPED_90_90,
    },
    {
        p = Vector2(11,3),
        a = 90,
        tl = EXTERIOR,
        tr = EXT_90V,
        bl = EXT_90H,
        br = EXT_90_90_CONVEX,
    },
],
